package_assets:         off          # (on, off, always)
embed_assets:           off          # (on, off, datauri)
compress_assets:        off          # (on, off)
gzip_assets:            off          # (on, off)
rewrite_relative_paths: off
# template_function:      _.template  # (defaults to the built-in micro-templating)
package_path:           /assets-compiled    # (defaults to assets)
javascript_compressor:  uglifier     # (yui, closure, uglifier)
# closure
# compressor_options:
#   compilation_level: ADVANCED_OPTIMIZATIONS

javascripts:
  header_scripts:
    - public/javascripts/vendor/modernizr-latest.js
    - public/javascripts/utils/utils.js
    - public/javascripts/utils/storage.js
  footer_scripts:
    - public/javascripts/vendor/jquery.js
    - public/javascripts/application.js
    - public/javascripts/gallery.js
    - public/javascripts/gallery_item.js

stylesheets:
  application:
    - public/stylesheets/application.css
